//==================================================
//     Outputs that match the input variables
//==================================================
output "name" {
  description = "The value of the `name` input variable."
  value       = var.name
}
output "authentication_types" {
  description = "The value of the `authentication_types` input variable."
  value       = var.authentication_types
}
output "schema" {
  description = "The value of the `schema` input variable. Not available until the schema apply is complete."
  value       = aws_appsync_graphql_api.this.schema
}
output "tags" {
  description = "The value of the `tags` input variable, or the default value if the input was `null`."
  value       = var.tags
}
output "openid_connect_config" {
  description = "The value of the `openid_connect_config` input variable, or the default value if the input was `null`."
  value       = var.openid_connect_config
}
output "user_pool_config" {
  description = "The value of the `user_pool_config` input variable, or the default value if the input was `null`."
  value       = var.user_pool_config
}
output "lambda_authorizer_config" {
  description = "The value of the `lambda_authorizer_config` input variable, or the default value if the input was `null`."
  value       = var.lambda_authorizer_config
}
output "logging_enabled" {
  description = "The value of the `logging_enabled` input variable, or the default value if the input was `null`."
  value       = var.logging_enabled
}
output "logging_level" {
  description = "The value of the `logging_level` input variable, or the default value if the input was `null`."
  value       = var.logging_level
}
output "log_retention_days" {
  description = "The value of the `log_retention_days` input variable, or the default value if the input was `null`."
  value       = var.log_retention_days
}
output "logging_exclude_verbose_content" {
  description = "The value of the `logging_exclude_verbose_content` input variable, or the default value if the input was `null`."
  value       = var.logging_exclude_verbose_content
}
output "xray_enabled" {
  description = "The value of the `xray_enabled` input variable, or the default value if the input was `null`."
  value       = var.xray_enabled
}
output "create_custom_domain" {
  description = "The value of the `create_custom_domain` input variable, or the default value if the input was `null`."
  value       = var.create_custom_domain
}
output "custom_domain" {
  description = "The value of the `custom_domain` input variable, or the default value if the input was `null`."
  value       = var.custom_domain
}
output "custom_domain_description" {
  description = "The value of the `custom_domain_description` input variable, or the default value if the input was `null`."
  value       = var.custom_domain_description
}
output "custom_domain_acm_certificate_arn" {
  description = "The value of the `custom_domain_acm_certificate_arn` input variable, or the default value if the input was `null`."
  value       = var.custom_domain_acm_certificate_arn
}
output "datasources" {
  description = "The value of the `datasources` input variable, or the default value if the input was `null`."
  value       = var.datasources
}
output "functions" {
  description = "The value of the `functions` input variable, or the default value if the input was `null`."
  value       = var.functions
}
output "unit_resolvers" {
  description = "The value of the `unit_resolvers` input variable, or the default value if the input was `null`."
  value       = var.unit_resolvers
}
output "pipeline_resolvers" {
  description = "The value of the `functpipeline_resolversions` input variable, or the default value if the input was `null`."
  value       = var.pipeline_resolvers
}

//==================================================
//       Outputs generated by this module
//==================================================
output "logging_role" {
  description = "The IAM role that the AppSync GraphQL API uses for CloudWatch logging."
  value       = aws_iam_role.appsync_logging
}
output "logging_policy" {
  description = "The IAM policy that is attached to the `logging_role` IAM role."
  value       = aws_iam_role_policy.appsync_logging
}
output "graphql_api" {
  description = "The GraphQL API resource that was created."
  value       = aws_appsync_graphql_api.this
}
output "api_graphql_endpoint" {
  description = "The GraphQL endpoint for this API."
  value       = var.create_custom_domain ? "https://${aws_appsync_domain_name.this[0].domain_name}/graphql" : aws_appsync_graphql_api.this.uris["GRAPHQL"]
}
output "api_realtime_endpoint" {
  description = "The GraphQL endpoint for this API."
  value       = var.create_custom_domain ? "wss://${aws_appsync_domain_name.this[0].domain_name}/graphql" : aws_appsync_graphql_api.this.uris["REALTIME"]
}
output "function_resources" {
  description = "A map of AppSync function resources that were created. The map keys correspond to the map keys in the `functions` input variable."
  value       = module.appsync_resolvers.functions
}
output "unit_resolver_resources" {
  description = "A map of AppSync unit resolver resources that were created. The map keys correspond to the map keys in the `unit_resolvers` input variable."
  value       = module.appsync_resolvers.unit_resolvers
}
output "pipeline_resolver_resources" {
  description = "A map of AppSync pipeline resolver resources that were created. The map keys correspond to the map keys in the `pipeline_resolvers` input variable."
  value       = module.appsync_resolvers.pipeline_resolvers
}
output "log_group" {
  description = "The CloudWatch log group resource that was created for the AppSync API."
  value       = aws_cloudwatch_log_group.this
}
output "custom_domain_hosted_zone" {
  description = "The ID of the hosted zone of the custom domain (used for a Route53 alias record)."
  value       = var.create_custom_domain ? aws_appsync_domain_name.this[0].hosted_zone_id : null
}
output "custom_domain_appsync_domain_name" {
  description = "The AppSync domain name for the custom domain (used for a Route53 alias record)."
  value       = var.create_custom_domain ? aws_appsync_domain_name.this[0].appsync_domain_name : null
}
